cclb_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cclb/', include('cclbapp.urls')),
       
]

cclbapp/urls.py
from django.urls import path 
from . import views 

app_name = "cclbapp"

urlpatterns = [
   path('', views.index, name='index'),
   path('howtograb', views.howtograb, name='howtograb'),
   path('properties', views.properties, name='properties'),
   path("register", views.register_request, name="register"),
   path("login", views.login_request, name="login"),
   path("logout", views.logout_request, name= "logout"),
]
   

cclbapp/models.py
from django.db import models

# Create your models here.

cclbapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

cclbapp/views.py
import re
import googlemaps
import simplekml
import pandas
import requests
from django.shortcuts import  render, redirect
from .forms import NewUserForm
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout

from django.shortcuts import render
from django.http import HttpResponse


def index(request):
    
    API_KEY = 'AIzaSyDaG1DJvvM8hq1mufzM4RI1tVDAGItwki0'

    gmaps = googlemaps.Client(API_KEY)
    
      
    return render(request, 'cclbapp/index.html')

def howtograb(request):
    return render(request, "cclbapp/howtograb.html")
def properties(request):
    return render(request, "cclbapp/properties.html")

def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("cclbapp:index")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()
    return render (request=request, template_name="cclbapp/register.html", context={"register_form":form})


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("cclbapp:index")
            else:
                messages.error(request,"Invalid username or password.")
    else:
        messages.error(request,"Invalid username or password.")
        form = AuthenticationForm()
    return render(request=request, template_name="cclbapp/login.html", context={"login_form":form})     

def logout_request(request):
    logout(request)
    messages.info(request, "You have successfully logged out.") 
    return redirect("cclbapp:index")   
   

# cclb =input("cclb: ")   
# data = csv.reader(open('cclb.csv'), delimiter= ',')
# kml = simplekml.Kml()

# f = open('csv2kml.kml', 'w')

# response = request.get("https://www.google.com/maps/d/u/1/edit?mid=1OGUQrsxmK96d7F78A-oQLIgtzBalSuDE&ll=33.52536647831128%2C-84.3528385&z=12")

cclbapp/templates/cclbapp/howtograb.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>How To Grab</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
    <div class="container">
        <div class="navbar-grab">             
        <nav>
        <a href="{% url 'cclbapp:index' %}" class="button">Home</a>
        <a href="{% url 'cclbapp:properties' %}" class="button">Properties</a                          
        
                                

    class="box">
    <br>
    <br>
    <br>
    <p>What Is A Land Bank:</p>
    <br>
    <p>The Land Bank is a statutory tool that partners with cities to return tax delinquent dilapidated, and abandon properties to productive use. Your local Land Bank Authority processes applications from interested governmental agencies, businesses and individuals, and conveys the desired properties for public use, or to be reintroduced into the revenue-producing tax rolls.<p>     
    <br>
    <br>
    <br>
    <p>Grab Your Property:<p>
    <p>Please note that every local Land Bank Authority has its own steps and procedures in acquiring Tax Deed and Title.  Please contact your local municipality office to for details.</p>
        </nav>
        </div>      
    
    </div>
  

</body>
</html>

cclbapp/templates/cclbapp/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Land Grab</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">

    {% comment %} <link rel="stylesheet" href="styles.css"> {% endcomment %}



    
</head>

<body>

    
  <div class="container">
        
    <div class="navbar">                       
        
      <div class="content">
        <p>Land Grab: Real Estate Investing For The Everyday Individual</p>
        <h1>Start Grabbing</h1>
        <a href="{% url 'cclbapp:properties' %}" class="button">Properties</a>
            
        <a href="{% url 'cclbapp:howtograb' %}" class="button">How To Grab</a>      
       
        {% if user.is_authenticated %}
      
          <div class="nav-item">
            <a href="{% url 'cclbapp:logout' %}" class="button">Logout</a>
               
          </div>  
        {% else %}

          <div class="nav-item">
            <a href="{% url 'cclbapp:login' %}" class="button">Login</a>
        
          </div>
        {% endif %}
            
      </div>

      <img src="{% static '/images/rightimage.jpg' %}" class="feature-img">

    </div>

  </div>


</body>
</html>

cclbapp/templates/cclbapp/login.html
{% load static %}
<link rel="stylesheet" href="{% static 'styles.css' %}">

<div class="container py-5">
    <h1>Login</h1>

    <form method="POST">

      {% csrf_token %}
      {{ login_form }}

      <button class="btn btn-primary" type="submit">Login</button>

    </form>
    <p class="text-center">Don't have an account? <a href="{% url 'cclbapp:register' %}">Create an account</a>.</p>
</div>

cclbapp/templates/cclbapp/properties.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Properties</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>

<body>
    <div class="container-frame">
    <a href="{% url 'cclbapp:index' %}" class="button">Home</a>
    <a href="{% url 'cclbapp:howtograb' %}" class="button">How To Grab</a>

        <br>
        <br>

    <iframe src="https://www.google.com/maps/d/u/1/embed?mid=1OGUQrsxmK96d7F78A-oQLIgtzBalSuDE&ehbc=2E312F" width="100%" height="800"></iframe>

    
    </div>

</body>

              
                    
               

cclbapp/templates/cclbapp/register.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
	<link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>

      

<!--Register--> 

<div class="container py-5">
	<h1>Register</h1>
	<form method="POST">
		{% csrf_token %}
		{{ register_form}}                    
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	<p class="text-center">If you already have an account, <a href="{% url 'cclbapp:login' %}">login</a> instead.</p>
</div>


</body>
</html>